/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    Loader: typeof import('./components/loader/index.vue')['default']
    Office: typeof import('./components/office/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UploadFile: typeof import('./components/uploadFile/index.vue')['default']
  }
}
